version: '3.7'

services:
  backend:
    build: .
    command: gunicorn --bind 0.0.0.0:6000 wsgi:app workers 4 --threads 4 -k gthread --timeout 10
    restart: always
    environment:
      - DOMAINS_DICT_PATH=${DOMAINS_DICT_PATH}
      - APP_ENV="production"
    volumes:
      - /tmp/:/tmp/
    ports:
      - 4350:6000